Able to register routes or not in the config
andreaselia/laravel-analytics pull request #39
Opened 2023-07-16 10:08 UTC by vincent-tarrit

Hello, I'm using filament so the route is not necessary in my case. I added a config params to remove this routes:) 

Thank you very much for your job ! It's great !

2023-07-16 10:11 UTC, andreaselia requested changes
Thanks @vincent-tarrit, I'm happy to add the ability to disable the route, but would need the config parameter adding to the config, as well as a test case if possible. StyleCI is also failing at the moment.

2023-07-16 10:13 UTC, vincent-tarrit commented
yes, sorry just added it :)

2023-07-16 14:13 UTC, andreaselia requested changes

2023-07-16 14:13 UTC, andreaselia commented on config/analytics.php
> +    ],
This isn't part of this PR.

2023-07-16 14:13 UTC, andreaselia commented on src/AnalyticsServiceProvider.php
> +        if (config('analytics.registerRoutes')){
Could you add a PHPUnit feature test for this?

2023-08-25 23:04 UTC, andreaselia commented
Hi mate, I'm closing this for the time being, feel free to re-open it in the future with the necessary changes. Thanks!

2023-08-25 23:04 UTC, closed without merging