add http host to page_views
andreaselia/laravel-analytics pull request #51
Opened 2024-03-22 17:09 UTC by myneid

add the http host for the use case of having multiple domains on the same codebase

2024-03-24 19:57 UTC, andreaselia commented
@myneid thanks for the PR, StyleCI is failing though.

2024-03-24 19:59 UTC, andreaselia requested changes

2024-03-24 19:59 UTC, andreaselia commented on database/migrations/2024_03_22_100000_add_host_to_page_views.php
> +
Remove blank line.

2024-03-24 19:59 UTC, andreaselia commented on src/Http/Middleware/Analytics.php
> +            'host' => $request->getHost(),
Match the arrow to the others.

2024-03-31 20:14 UTC, andreaselia approved these changes

2024-03-31 20:14 UTC, merged

2024-03-31 20:15 UTC, andreaselia commented
Thanks for your PR @myneid 👍

2024-04-01 19:29 UTC, myneid commented
sorry, i thought i had used intellesense formatting automatically. meant to get back to this. thank you for this great package

2024-04-01 20:02 UTC, andreaselia commented
All good mate, thought I'd just quickly sort it out so others can make use of it too.

You're welcome, and thank you for contributing to make it an even greater package 💪